const BannerRouter = require("./routes/banner.route.js");
const AboutUsRouter = require("./routes/aboutUs.route.js");
const BrochureRouter = require("./routes/brochure.route.js");
const ProfileRouter = require("./routes/profile.route.js");
const ContactRouter = require("./routes/contact.route.js");
const DevelopmentProcessRouter = require("./routes/developmentProcess.route.js");
const ExperienceRouter = require("./routes/experience.route.js");
const GalleryRouter = require("./routes/gallery.route.js");
const LatestGalleryRouter = require("./routes/latestGallery.route.js");
const VideoRouter = require("./routes/video.route.js");
const OurValuesRouter = require("./routes/ourValues.route.js");
const ServiceRouter = require("./routes/service.route.js");
const AuthRouter = require("./routes/auth.route.js");
const BlogRouter = require("./routes/blog.route.js");
const EventRouter = require("./routes/event.route.js");
const TeamRouter = require("./routes/team.route.js");
const CareerRouter = require("./routes/career.route.js");
const PublicationRouter = require("./routes/publication.route.js");
const JobApplicantRouter = require("./routes/jobApplicant.route.js");

const { Router } = require("express");
const rootRouter = Router();
rootRouter.use("/banners", BannerRouter);
rootRouter.use("/about-us", AboutUsRouter);
rootRouter.use("/brochure", BrochureRouter);
rootRouter.use("/profile", ProfileRouter);
rootRouter.use("/contact", ContactRouter);
rootRouter.use("/development-process", DevelopmentProcessRouter);
rootRouter.use("/experience", ExperienceRouter);
rootRouter.use("/gallery", GalleryRouter);
rootRouter.use("/latest-gallery", LatestGalleryRouter);
rootRouter.use("/video", VideoRouter);
rootRouter.use("/our-values", OurValuesRouter);
rootRouter.use("/service", ServiceRouter);
rootRouter.use("/auth", AuthRouter);
rootRouter.use("/news", BlogRouter);
rootRouter.use("/events", EventRouter);
rootRouter.use("/publications", PublicationRouter);
rootRouter.use("/team", TeamRouter);
rootRouter.use("/careers", CareerRouter);
rootRouter.use("/job-applicants", JobApplicantRouter);
module.exports = rootRouter;
